"""Deterministic API manifest generation."""

from appwright.api.specification import ApiSpecification


def quoted(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def tuple_source(values: tuple[str, ...]) -> str:
    entries = ", ".join(quoted(value) for value in values)
    suffix = "," if len(values) == 1 else ""
    return f"({entries}{suffix})"


def render_manifest(specification: ApiSpecification) -> str:
    lines = [
        "# Generated by scripts/generate_api.py. Do not edit directly.",
        '"""Generated Pydantic API surface manifest."""',
        "",
        "from appwright.api.specification import ApiClass, ApiSpecification",
        "",
        "API_SURFACE = ApiSpecification(",
        "    classes=(",
    ]
    for api_class in specification.classes:
        class_name = quoted(api_class.name)
        methods = tuple_source(api_class.methods)
        single_line = f"        ApiClass(name={class_name}, methods={methods}),"
        if len(single_line) <= 100:
            lines.append(single_line)
        elif len(api_class.methods) <= 5:
            lines.extend(
                (
                    "        ApiClass(",
                    f"            name={class_name}, methods={methods}",
                    "        ),",
                )
            )
        else:
            lines.extend(
                (
                    "        ApiClass(",
                    f"            name={class_name},",
                    "            methods=(",
                )
            )
            for method in api_class.methods:
                lines.append(f"                {quoted(method)},")
            lines.extend(("            ),", "        ),"))
    lines.extend(("    )", ")", ""))
    return "\n".join(lines)
